### ISSUE TITLE
Response invalid on safetynet

### ISSUE THREAD

**Issue by smartymcfly** [Magisk-Modules-Repo/disable-screenshot-camera-sounds#1]
This modules causes safety net to return an invalid response.  It does not say failed.  It says response invalid.

**Comment by smartymcfly** [comment]
Pixel 3 xl, Android 9.0, magisk 18.1b

**Comment by ant9000** [comment]
Passing all Safety Net tests here, on LineageOS 14.1 with Magisk 18. I really doubt that 'response invalid' could be related to this module - it just truncates two audio files to zero length. Maybe your problem lies elsewhere?
