### ISSUE TITLE
Not working on Pixel 3a

### ISSUE THREAD

**Issue by creeve4** [Magisk-Modules-Repo/disable-screenshot-camera-sounds#3]
This module does not disable the screenshot sound on my Pixel 3a

**Comment by ant9000** [comment]
I'll be glad to add it to the masked out sounds, but unfortunately can't do it for every device/ROM combination without your help.

Can you identify which specific file is involved on your Pixel 3a (and in your ROM) and drop a line?

Thank you for your help,

Antonio

**Comment by creeve4** [comment]
The file is the same "camera_click.ogg", but the location is different: system\product\media\audio\ui\camera_click.ogg

**Comment by compliment** [comment]
@ant9000 Please review and merge.
